name: Install riscv64-linux-musl-cc toolchain

runs:
  steps:
  - name: Attempt to restore toolchain from cache
    id: cache
    uses: actions/cache@v4
    with:
      path: riscv64-linux-musl-cross
      key: riscv64-musl-cache
      restore-keys: |
        riscv64-musl-

  - name: Download musl toolchain
    if: steps.cache.outputs.cache-hit != 'true'
    shell: bash
    run: |
      wget https://musl.cc/riscv64-linux-musl-cross.tgz
      tar -xf riscv64-linux-musl-cross.tgz

  - name: Cache sdcard.img if not cached
    if: steps.cache.outputs.cache-hit != 'true'
    uses: actions/cache@v4
    with:
      path: riscv64-linux-musl-cross
      key: riscv64-musl-cache

  - name: Add toolchian to PATH
    shell: bash
    run: |
      echo "$PWD/riscv64-linux-musl-cross/bin" >> $GITHUB_PATH

  - name: Verify installation
    shell: bash
    run: riscv64-linux-musl-cc --version
