[package]
name = "linux-task"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hermit-sync = "0.1.6"
linux-task-abstractions = { path = "../linux-task-abstractions", default-features = false }
memory-space = { path = "../memory-space", default-features = false }
filesystem-abstractions = { path = "../filesystem-abstractions", default-features = false }
trap-abstractions = { path = "../trap-abstractions", default-features = false }
task-abstractions = { path = "../task-abstractions", default-features = false }
mmu-abstractions = { path = "../mmu-abstractions", default-features = false }
linux-loader = { path = "../linux-loader", default-features = false }

address = { path = "../address", default-features = false }
platform-specific = { path = "../platform-specific", default-features = false }

[features]
default = ["no_std"]
std = []
no_std = []
