name: Setup Rust

inputs:
  targets:
    required: false
  target:
    required: false
  components:
    required: false

runs:
  using: composite
  steps:
    - name: Extract Rust channel from rust-toolchain.toml
      shell: bash
      id: rust-channel
      run: |
        CHANNEL=$(grep -E '^channel\s*=' rust-toolchain.toml | \
                    sed -E 's/^channel\s*=\s*"([^"]+)"\s*$/\1/' | \
                    tr -d '[:space:]')

        echo "rust_channel=$CHANNEL" >> $GITHUB_OUTPUT

    - name: Display install details
      shell: bash
      run: |
        echo "Installing Rust ${{ steps.rust-channel.outputs.rust_channel }}"
        echo "Targets: ${{ inputs.targets || 'default' }}"
        echo "Target: ${{ inputs.target || 'default' }}"
        echo "Components: ${{ inputs.components || 'none' }}"

    - name: Install Rust (with targets and components if provided)
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ steps.rust-channel.outputs.rust_channel }}
        targets: ${{ inputs.targets || '' }}
        target: ${{ inputs.target || '' }}
        components: ${{ inputs.components || '' }}
