[package]
name = "bakaos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
constants = { path = "../crates/constants", default-features = false }
address = { path = "../crates/address", default-features = false }
path = { path = "../crates/path", default-features = false }
allocation = { path = "../crates/allocation", default-features = false }
timing = { path = "../crates/timing", default-features = false }
drivers = { path = "../crates/drivers", default-features = false }
filesystem-abstractions = { path = "../crates/filesystem-abstractions", default-features = false }
filesystem = { path = "../crates/filesystem", default-features = false }
paging = { path = "../crates/paging", default-features = false }
log = "0.4.22"
sbi-rt = "0.0.3"
sbi-spec = "0.0.7"
riscv = "0.12.1"
buddy_system_allocator = { git = "https://github.com/neuq-rcore/buddy_system_allocator" }
virtio-drivers = "0.7.5"

[features]
default = ["virt"]
virt = []
vf2 = []
