name: Install Qemu

runs:
  using: composite
  steps:
  - name: Attempt to restore toolchain from cache
    id: cache
    uses: actions/cache@v4
    with:
      path: qemu
      key: qemu-cache
      restore-keys: qemu-

  - name: Download musl toolchain
    if: steps.cache.outputs.cache-hit != 'true'
    shell: bash
    run: |
      mkdir qemu
      wget -P qemu https://github.com/neuq-rcore/testsuit-binary/releases/download/qemu/qemu-prebuilt-7.0.0.tar.gz
      wget -P qemu https://github.com/neuq-rcore/testsuit-binary/releases/download/qemu/qemu-loongarch64.tgz

  - name: Cache sdcard.img if not cached
    if: steps.cache.outputs.cache-hit != 'true'
    uses: actions/cache@v4
    with:
      path: qemu
      key: qemu-cache

  - name: Install and Add qemu to PATH
    shell: bash
    run: |
      cd qemu
      mkdir qemu-riscv64
      tar -xf qemu-prebuilt-7.0.0.tar.gz -C qemu-riscv64
      tar -xf qemu-loongarch64.tgz
      echo "$PWD/qemu-riscv64/bin" >> $GITHUB_PATH
      echo "$PWD/qemu-loongarch64/bin" >> $GITHUB_PATH

  - name: Verify installation
    shell: bash
    run: |
      qemu-system-riscv64 --version
      qemu-system-loongarch64 --version
