name: Cache Warmup

on:
  # GitHub will remove any cache entries that have not been accessed in over 7 days
  # We access the cache every 24 hours to prevent deletion
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cache-maintenance:
    runs-on: ubuntu-latest

    steps:

    # Try access the cache to keep it alive. 
    - name: Attempt to restore sdcard.img.zst from cache
      id: cache
      uses: actions/cache@v4
      with:
        path: sdcard.img.zst
        key: sdcard-img-cache
        restore-keys: |
          sdcard-img-

    # Cache sdcard.img if it was not found in the cache. This should be rare, but ensures other CI jobs run quickly.
    - name: Download .img file if not cached
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -L -o sdcard.img.zst "${{ secrets.SDCARD_FINAL_URL }}"

    - name: Assert that we have the sdcard.img
      run: ls -lh sdcard.img.zst

    # GitHub will compress the files, so we just submit the original .img file. 
    - name: Cache sdcard.img
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache@v4
      with:
        path: sdcard.img.zst
        key: sdcard-img-cache
  
    - name: Assert that the file is in good shape  
      id: assert_file
      run: |
        # Check that the file is not corrupted
        file sdcard.img.zst

        # Extract sdcard.img
        zstd -d sdcard.img.zst -o sdcard.img

        ls -lh sdcard.img
        file sdcard.img

        # Mount the file to check that it is a valid image
        mkdir mnt
        sudo mount -o loop sdcard.img mnt
        ls -lh mnt
        sudo umount mnt

    # Pull from Azure if the cache was corrupted.
    - name: Download .img file if corrupted
      if: steps.assert_file.outcome == 'failure'
      run: |
        curl -L -o sdcard.tar.gz "${{ secrets.SDCARD_FINAL_URL }}"

    # Cache the new file if the cache was corrupted.    
    - name: Cache sdcard.img if corrupted
      if: steps.assert_file.outcome == 'failure'
      uses: actions/cache@v4
      with:
        path: sdcard.img.zst
        key: sdcard-img-cache
