name: Crates Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    paths:
      - 'crates/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: 'always'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./crates

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        env: 
            TOOLCHAIN_VERSION: nightly-2025-01-18
        run: |
          rustup toolchain install $TOOLCHAIN_VERSION --profile minimal
          rustup default $TOOLCHAIN_VERSION
          rustup override set $TOOLCHAIN_VERSION


      - name: Run tests
        run: cargo test --all
