name: Final test

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: 'always'
  IS_CI_ENVIRONMENT: true

jobs:
  run:
    name: Grading
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture:
          - { triplet: riscv64gc-unknown-none-elf, fullname: riscv64, shortname: rv }
#          - { triplet: loongarch64-unknown-none, fullname: loongarch64, shortname: la }

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        env: 
            TOOLCHAIN_VERSION: nightly-2025-01-18
        run: |
          rustup toolchain install $TOOLCHAIN_VERSION --profile minimal
          rustup default $TOOLCHAIN_VERSION
          rustup override set $TOOLCHAIN_VERSION
          rustup target add ${{ matrix.architecture.triplet }}
          rustup component add llvm-tools

      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-binutils

      - uses: ./.github/workflows/actions/setup-musl

      - name: Build Kernel
        run: make build-final ARCH=${{ matrix.architecture.fullname }}
      
      - uses: ./.github/workflows/actions/setup-qemu

      # Try access the cache to keep it alive. 
      - name: Attempt to restore sdcard.img.zst from cache
        id: cache
        uses: actions/cache@v4
        with:
          path: sdcard.img.zst
          key: sdcard-img-cache
          restore-keys: |
            sdcard-img-

      # Cache sdcard.img if it was not found in the cache. This should be rare, but ensures other CI jobs run quickly.
      - name: Download .img file if not cached
        if: steps.cache.outputs.cache-hit != 'true'
        run: curl -L -o sdcard.img.zst "${{ secrets.SDCARD_FINAL_URL }}"

      - name: Cache sdcard.img if not cached
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: sdcard.img.zst
          key: sdcard-img-cache

      - name: Extract sdcard.img
        run: zstd -d sdcard.img.zst -o sdcard-rv.img

      - name: Run tests
        timeout-minutes: 5 # A temporary value
        run: make _test_internal ARCH=${{ matrix.architecture.fullname }}

      - uses: actions/upload-artifact@v4
        with:
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          name: output-${{ matrix.architecture }}.log
          path: output.log
          if-no-files-found: error
          compression-level: 0
          overwrite: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet run --project KernelAnnotationBot -- -f=output.log
