name: Code Quality

on:
  push:
  pull_request:

jobs:
  inspect:
    name: Inspect
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - { prettyname: Cross Platform, triplet: x86_64-unknown-linux-gnu, cwd: '.' }
          - { prettyname: RISC-V64, triplet: riscv64gc-unknown-none-elf, cwd: 'kernel' }
          - { prettyname: LoongArch64, triplet: loongarch64-unknown-none, cwd: 'kernel' }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: ./.github/workflows/actions/setup-rust
        with:
          target: ${{ matrix.target.triplet }}
          components: 'clippy,rustfmt'

      - name: Remove rust-toolchain.toml
        shell: bash
        run: rm rust-toolchain.toml

      - name: Compile
        working-directory: ${{ matrix.target.cwd }}
        run: cargo build --target ${{ matrix.target.triplet }}

      - name: Inspect
        working-directory: ${{ matrix.target.cwd }}
        run: cargo fmt -- --check

      - name: Run Clippy
        working-directory: ${{ matrix.target.cwd }}
        if: ${{ !cancelled() }}
        run: cargo clippy --target ${{ matrix.target.triplet }} -- -D warnings
