name: Annotate

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

permissions:
  pull-requests: write
  checks: write

jobs:
  annotate:
    name: Annotate test results
    runs-on: ubuntu-latest
    if: ${{ !cancelled() && github.event.workflow_run.conclusion != 'skipped' }}
    timeout-minutes: 5

    steps:
      - name: Download test results
        uses: actions/download-artifact@v5
        with:
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
          pattern: test-results-*
          merge-multiple: true

      - name: Create GitHub App token
        uses: actions/create-github-app-token@v2
        id: app-token
        if: ${{ vars.APP_ID != '' }}
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Fetch pull request id
        run: |
          HEAD_PR=`gh pr list --search "${{ github.event.workflow_run.head_sha }}" --json number --jq '.[0].number'`
          echo "PULL_REQUEST_ID=$HEAD_PR" >> $GITHUB_ENV

      - name: Annotate CI run with test results
        uses: mikepenz/action-junit-report@v5
        if: ${{ always() }}
        with:
          check_name: Test Results
          report_paths: test-results-*/junit.xml
          include_time_in_summary: true
          truncate_stack_traces: false
          check_title_template: "{{SUITE_NAME}}::{{TEST_NAME}}"
          # regarding the reason of the wird searchValue, see https://github.com/caiyih/bakaos/pull/77
          transformers: |
            [{"searchValue":"\\\\\\","replaceValue":"/"}]
          detailed_summary: true
          follow_symlink: true
          token: ${{ steps.app-token.outputs.token || github.token }}
          pr_id: ${{ env.PULL_REQUEST_ID }}
          comment: ${{ env.PULL_REQUEST_ID != '' }}
