name: Annotate CI run with test results
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

permissions:
  contents: read
  actions: read
  pull-requests: write
  checks: write

jobs:
  annotate:
    name: Annotate CI run with test results
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}

      # 'github-token' is required when downloading artifacts from a different repository or from a different workflow run.
      - name: Download test results
        uses: actions/download-artifact@v5
        with:
          pattern: test-results-*
          merge-multiple: false
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      # When the triggering workflow is running in a restricted security context, some
      # data is omitted from `github.event.workflow_run` (including `pull_requests`).
      # Therefore, we have to take some extra steps to find out the PR that triggered
      # the original workflow. The simplest way is to iterate through our open PRs and
      # find the one with the same head SHA as the triggering workflow.
      - name: Try to find PR number
        id: get-pr-number
        uses: actions/github-script@v7
        with:
          script: |
            const per_page = 100;

            const head_sha = "${{ github.event.workflow_run.head_sha }}";
            console.log("Finding PR for SHA:", head_sha);

            let page = 1;

            while (true) {
                console.log("Loading Page:", page);

                const { data: prs } = await github.rest.pulls.list({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    per_page: per_page,
                    page: page,
                    state: "open",
                    sort: "updated",
                    direction: "desc",
                });

                const pr = prs.find(pr => pr.head.sha === head_sha);

                if (pr) {
                    console.log("Found PR:", pr.number);
                    return pr.number;
                }

                if (prs.length < per_page) {
                    break;
                }

                page++;
            }

      - name: Annotate CI run with test results
        uses: mikepenz/action-junit-report@v5
        with:
          check_name: Test Results
          report_paths: test-results-*/junit.xml
          commit: ${{ github.event.workflow_run.head_sha }}
          include_time_in_summary: true
          truncate_stack_traces: false
          check_title_template: "{{SUITE_NAME}}::{{TEST_NAME}}"
          transformers: |
            [{"searchValue":"\\\\","replaceValue":"/"}]
          detailed_summary: true
          follow_symlink: true
          comment: true
          pr_id: ${{ steps.get-pr-number.outputs.result }}
