name: Annotate CI run with test results
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  annotate:
    name: Annotate CI run with test results
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}

      # 'github-token' is required when downloading artifacts from a different repository or from a different workflow run.
      - name: Download test results
        uses: actions/download-artifact@v5
        with:
          pattern: test-results-*
          merge-multiple: false
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Annotate CI run with test results
        uses: mikepenz/action-junit-report@v5
        with:
          name: Results
          report_paths: test-results-*/junit.xml
          commit: ${{ github.event.workflow_run.head_sha }}
          truncate_stack_traces: false
          check_annotations: true
          detailed_summary: true
          follow_symlink: true
          update_check: true
          group_suite: true
          comment: true
